version: '2'
services:
  firebird:
    container_name: farmmix_firebird_server
    image: jacobalberty/firebird:2.5-sc
    ports:
      - "3050:3050"
    volumes_from:
      - data
  data:
    container_name: farmmix_firebird_data
    image: busybox
    volumes:
        - ./data:/databases
    command: tail -f /dev/null
